apiVersion: v1
kind: Service
metadata: 
  name: svc
  namespace: move
spec:
  type: NodePort
  selector:
    #app.kubernetes.io/name: MyApp
    app: nginx
  ports:
     - protocol: TCP
       port: 90
       targetPort: 90
