apiVersion: v1
kind: Service
metadata: 
  name: svc
  namespace: move
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: MyApp
  ports:
     - protocol: TCP
       port: 80
       targetPort: 80
       nodeport: 30009
