apiVersion: v1
kind: Service
metadata: 
  name: test-svc
  namespace: move
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
     - protocol: TCP
       port: 80
       targetPort: 9376
  type: NodePort
